server:
  port: 8080
  address: 0.0.0.0

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/academia?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: sail
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update   # cria/atualiza as tabelas automaticamente
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        # opcional, mas bom ter:
        dialect: org.hibernate.dialect.MySQL8Dialect

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

jwt:
  secret: minha-chave-secreta-muito-segura-com-pelo-menos-256-bits-de-tamanho-para-jwt
  expiration: 86400000  # 24 horas em milissegundos

abacatepay:
  base-url: https://api.abacatepay.com/v1
  api-key: abc_dev_RtwYxCr1ADruntuDYPqhpdrX
  webhook-secret: ${ABACATEPAY_WEBHOOK_SECRET:}
  return-url: ${ABACATEPAY_RETURN_URL:http://localhost:8001/views/premium/index.html}
  completion-url: ${ABACATEPAY_COMPLETION_URL:http://localhost:8001/views/premium/sucesso.html}



